// src/lib/mock-data.ts
// Allorea Cosmetics — demo / fallback verileri
// Tüm Unsplash URL'leri auto=format&fit=crop parametreli — güvenilir format

import type { Product, Category, BlogPost } from '@/types'

// ─── Kategoriler ──────────────────────────────────────────────────────────────
export const CATEGORIES: Category[] = [
  {
    id: '1', name: 'Skincare', slug: 'skincare',
    description: 'Cildinizi besleyin ve koruyun',
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: '2', name: 'Makeup', slug: 'makeup',
    description: 'Güzelliğinizi ifade edin',
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: '3', name: 'Body Care', slug: 'body-care',
    description: 'Baştanbaşa lüks bakım',
    image: 'https://images.unsplash.com/photo-1570194065650-d99fb4b38afc?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: '4', name: 'Fragrance', slug: 'fragrance',
    description: 'Hikayenizi anlatan kokular',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683702?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: '5', name: 'Hair Care', slug: 'hair-care',
    description: 'Evde salon kalitesi',
    image: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: '6', name: 'Serums', slug: 'serums',
    description: 'Yoğunlaştırılmış etki',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80',
  },
]

// ─── Ürünler ──────────────────────────────────────────────────────────────────
export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Allorea Radiance Serum',
    slug: 'allorea-radiance-serum',
    description: 'C vitamini kompleksi ile formüle edilmiş bu güçlü aydınlatıcı serum, cilt dokusunu düzelterek doğal parlaklık verir. Her damla cildinizi yeniler.',
    ingredients: 'Askorbik Asit %15, Niasinamid %5, Hyalüronik Asit, Ferulik Asit, Tokoferol',
    price: 89.00,
    comparePrice: 110.00,
    sku: 'ALR-SER-001',
    stock: 45,
    isActive: true, isFeatured: true, isBestSeller: true, isNew: false,
    category: { id: '6', name: 'Serums', slug: 'serums' },
    images: [
      { id: '1', url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80', alt: 'Allorea Radiance Serum', position: 0 },
      { id: '2', url: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=800&q=80', alt: 'Serum dokusu', position: 1 },
      { id: '3', url: 'https://images.unsplash.com/photo-1601049541271-d2dd2a8ef05b?auto=format&fit=crop&w=800&q=80', alt: 'Ürün detayı', position: 2 },
    ],
    averageRating: 4.8, reviewCount: 234,
    tags: ['çok-satan', 'c-vitamini', 'aydınlatıcı'],
    createdAt: '2024-01-15', updatedAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Kadife Gül Dudak Bakımı',
    slug: 'kadife-gul-dudak-bakimi',
    description: 'Gül yağı ve shea yağıyla zenginleştirilmiş bu dudak tedavisi, anında nem sağlar ve uzun süreli koruma sunar. İpeksi yumuşaklık.',
    price: 32.00,
    sku: 'ALR-LIP-002',
    stock: 78,
    isActive: true, isFeatured: true, isBestSeller: false, isNew: true,
    category: { id: '2', name: 'Makeup', slug: 'makeup' },
    images: [
      { id: '4', url: 'https://images.unsplash.com/photo-1586495777744-4e6232bf2b18?auto=format&fit=crop&w=800&q=80', alt: 'Kadife Gül Dudak Bakımı', position: 0 },
      { id: '5', url: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80', alt: 'Dudak bakımı uygulaması', position: 1 },
    ],
    averageRating: 4.6, reviewCount: 89,
    tags: ['dudak', 'nemlendirici', 'gül'],
    createdAt: '2024-02-10', updatedAt: '2024-02-10',
  },
  {
    id: '3',
    name: 'Gece Onarım Kremi',
    slug: 'gece-onarim-kremi',
    description: 'Retinol ve peptit kompleksiyle hazırlanan bu gece kremi, uyurken cildinizi yeniler. Sabah uyanışında görünür tazelik ve pürüzsüzlük.',
    ingredients: 'Retinol %0.3, Bakuchiol, Peptit Kompleksi, Shea Yağı, Squalane',
    price: 115.00,
    comparePrice: 140.00,
    sku: 'ALR-CRM-003',
    stock: 32,
    isActive: true, isFeatured: true, isBestSeller: true, isNew: false,
    category: { id: '1', name: 'Skincare', slug: 'skincare' },
    images: [
      { id: '6', url: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?auto=format&fit=crop&w=800&q=80', alt: 'Gece Onarım Kremi', position: 0 },
      { id: '7', url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80', alt: 'Krem dokusu', position: 1 },
    ],
    averageRating: 4.9, reviewCount: 312,
    tags: ['çok-satan', 'anti-aging', 'retinol'],
    createdAt: '2024-01-20', updatedAt: '2024-01-20',
  },
  {
    id: '4',
    name: 'Saten Cilt Vücut Yağı',
    slug: 'saten-cilt-vucut-yagi',
    description: 'Argan ve jojoba yağları karışımından oluşan bu lüks vücut yağı, cildi besler ve ışıltılı bir parlaklık verir. Saf lüks.',
    price: 68.00,
    sku: 'ALR-BOD-004',
    stock: 56,
    isActive: true, isFeatured: false, isBestSeller: true, isNew: false,
    category: { id: '3', name: 'Body Care', slug: 'body-care' },
    images: [
      { id: '8', url: 'https://images.unsplash.com/photo-1570194065650-d99fb4b38afc?auto=format&fit=crop&w=800&q=80', alt: 'Saten Cilt Vücut Yağı', position: 0 },
    ],
    averageRating: 4.7, reviewCount: 156,
    tags: ['vücut', 'yağ', 'parlaklık'],
    createdAt: '2024-02-01', updatedAt: '2024-02-01',
  },
  {
    id: '5',
    name: 'Bulut Yumuşaklığında Pudra',
    slug: 'bulut-yumusakliginda-pudra',
    description: 'Nefes alan mikro-silika formülü ile bu ayar pudrası, günün yorgunluğunu alırken cildi mat ve pürüzsüz bırakır.',
    price: 48.00,
    sku: 'ALR-MKP-005',
    stock: 89,
    isActive: true, isFeatured: false, isBestSeller: false, isNew: true,
    category: { id: '2', name: 'Makeup', slug: 'makeup' },
    images: [
      { id: '9', url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80', alt: 'Bulut Yumuşaklığında Pudra', position: 0 },
    ],
    averageRating: 4.5, reviewCount: 178,
    tags: ['pudra', 'ayar', 'makyaj'],
    createdAt: '2024-03-01', updatedAt: '2024-03-01',
  },
  {
    id: '6',
    name: 'Fleur Blanche Eau de Parfum',
    slug: 'fleur-blanche-eau-de-parfum',
    description: 'Bergamot üst notası, jasmin kalp notu ve sandal ağacı taban notasıyla oluşturulan bu özel koku, günün her saatine eşlik eder.',
    price: 195.00,
    comparePrice: 220.00,
    sku: 'ALR-FRG-006',
    stock: 23,
    isActive: true, isFeatured: true, isBestSeller: false, isNew: false,
    category: { id: '4', name: 'Fragrance', slug: 'fragrance' },
    images: [
      { id: '10', url: 'https://images.unsplash.com/photo-1541643600914-78b084683702?auto=format&fit=crop&w=800&q=80', alt: 'Fleur Blanche Eau de Parfum', position: 0 },
    ],
    averageRating: 4.9, reviewCount: 67,
    tags: ['parfüm', 'çiçeksi', 'lüks'],
    createdAt: '2024-01-05', updatedAt: '2024-01-05',
  },
  {
    id: '7',
    name: 'Hydra Boost Nemlendirici',
    slug: 'hydra-boost-nemlendirici',
    description: '5 katlı hyalüronik asit kompleksi ile cildinizin derinliklerine nem veren bu nemlendirici, 72 saate kadar uzun süreli hidrasyon sağlar.',
    price: 75.00,
    sku: 'ALR-SKN-007',
    stock: 112,
    isActive: true, isFeatured: false, isBestSeller: true, isNew: false,
    category: { id: '1', name: 'Skincare', slug: 'skincare' },
    images: [
      { id: '11', url: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=800&q=80', alt: 'Hydra Boost Nemlendirici', position: 0 },
    ],
    averageRating: 4.7, reviewCount: 445,
    tags: ['nemlendirici', 'hyalüronik-asit', 'nem'],
    createdAt: '2024-01-25', updatedAt: '2024-01-25',
  },
  {
    id: '8',
    name: 'İpek Onarım Saç Maskesi',
    slug: 'ipek-onarim-sac-maskesi',
    description: 'Keratin ve argan yağı ile zenginleştirilmiş bu saç maskesi, hasarlı saçları onarır ve özlü bir parlaklık kazandırır.',
    price: 55.00,
    comparePrice: 68.00,
    sku: 'ALR-HAR-008',
    stock: 67,
    isActive: true, isFeatured: false, isBestSeller: false, isNew: true,
    category: { id: '5', name: 'Hair Care', slug: 'hair-care' },
    images: [
      { id: '12', url: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&w=800&q=80', alt: 'İpek Onarım Saç Maskesi', position: 0 },
    ],
    averageRating: 4.6, reviewCount: 98,
    tags: ['saç', 'onarım', 'keratin'],
    createdAt: '2024-03-10', updatedAt: '2024-03-10',
  },
]

// ─── Blog Yazıları ─────────────────────────────────────────────────────────────
export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'C Vitamini: Cilt Bakımının Altın Standardı',
    slug: 'c-vitamini-cilt-bakiminin-altin-standardi',
    excerpt: 'C vitamini neden en güçlü antioksidanlardan biridir ve sabah rutininize nasıl dahil etmelisiniz?',
    content: 'C vitamini, dermatolojinin uzun zamandır değer verdiği bir bileşendir...',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    authorName: 'Dr. Isabelle Laurent',
    tags: ['cilt-bakımı', 'malzemeler', 'c-vitamini'],
    publishedAt: '2024-05-15',
    createdAt: '2024-05-15',
  },
  {
    id: '2',
    title: 'Yeni Başlayanlar İçin Cilt Bakım Rutini',
    slug: 'yeni-baslayanlar-icin-cilt-bakim-rutini',
    excerpt: 'Cilt bakımına nereden başlayacağınızı bilmiyor musunuz? İşte adım adım rehberiniz.',
    content: 'Etkili bir cilt bakım rutini oluşturmak göz korkutucu görünebilir...',
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80',
    authorName: 'Sophia Chen',
    tags: ['cilt-bakımı', 'rutin', 'başlangıç'],
    publishedAt: '2024-05-08',
    createdAt: '2024-05-08',
  },
]
